### ISSUE TITLE
console blanks when running coolgpus

### ISSUE THREAD

**Issue by eugeneware** [andyljones/coolgpus#11]
Thanks so much for creating coolgpus. It's been a great tool for keeping our multi-GPU machine cool.

I have a monitor plugged into my first GPU which usually shows a console which is useful for getting access to our server if there are any hardware problems.

But after launch coolgpus that display goes blank and unresponsive. When I kill coolgpus the console returns.

Is  there a way to configure the xorg.conf files or make any other changes to prevent this from happening? 

Thanks for any help you can offer and for the great tool you've written.

**Comment by v-iashin** [comment]
Hi

We have a similar setup as you describe and we also face the same issue. I think this is tracked in https://github.com/andyljones/coolgpus/issues/1 and still unsolved.

**Comment by andyljones** [comment]
As @v-iashin says, this is (unfortunately) expected behaviour. #1 'tracks progress', but because (a) my own machine is headless and (b) partially-headless seems to be a *lot* trickier than entirely-headless, it's likely to remain unresolved for the foreseeable future.
