### ISSUE TITLE
Server already active and failed to close it

### ISSUE THREAD

**Issue by Elikill58** [andyljones/coolgpus#17]
I'm trying to set all fans to 100%.

Result of **sudo $(which coolgpus) --speed 99 99** :
```
Traceback (most recent call last):
  File "/usr/local/bin/coolgpus", line 266, in <module>
    run()
  File "/usr/local/bin/coolgpus", line 259, in run
    with xservers(buses) as displays:
  File "/usr/lib/python3.8/contextlib.py", line 113, in __enter__
    return next(self.gen)
  File "/usr/local/bin/coolgpus", line 172, in xservers
    kill_xservers()
  File "/usr/local/bin/coolgpus", line 163, in kill_xservers
    raise IOError('There are already X servers active. Either run the script with the `--kill` switch, or kill them yourself first')
OSError: There are already X servers active. Either run the script with the `--kill` switch, or kill them yourself first
```

Result of **sudo $(which coolgpus) --speed 99 99 --kill** :
```
Killing all running X servers, including 1671
Awaiting X server shutdown
Awaiting X server shutdown
Awaiting X server shutdown
Awaiting X server shutdown
```

I don't know how to find the server, and close it myself.

**Comment by v-iashin** [comment]
Have you already tried to kill 1671 (the pid from the error)?


---
As a side note, sometimes I have a similar issue when coolgpus fails all of the sudden during a heavy load. 

I tried a crazy number of different approaches but only a reboot fixes it for me. Did you have similar experience by any chance? 

Keep me updated if you will find a work-around.

**Comment by Elikill58** [comment]
> Have you already tried to kill 1671 (the pid from the error)?

With `ps aux | grep 1671` and I didn't find any process.

> I tried a crazy number of different approaches but only a reboot fixes it for me. Did you have similar experience by any chance?

It's the first time that I launch it so idk

**Comment by Paethon** [comment]
@v-iashin I have seen similar behaviour. `coolgpus` often just crashes after a few hours/days. 

We tried solving this by calling coolgpus in a loop if it exits. Recently, this leads to zombie X-Server processes that can't be killed anymore and the only way of getting everything to work again is to reboot the system, which is a bit cumbersome for a server, used by multiple people etc.

**Comment by Elikill58** [comment]
Can I close this issue ?
