### ISSUE TITLE
Fan control for cards with multiple addressable fans

### ISSUE THREAD

**Issue by chstan** [andyljones/coolgpus#18]
It would be better if there were a way to control both fan zones on cards that support this. On a local copy of the repo I get around this by parsing the addressable fans for each card according to the contents of

```
$> nvidia-settings -q all
```

and then issuing the appropriate update commands in `set_speed`. This is a relatively minor fix, but handling this appropriately on multi-GPU machines may be more involved.

**Comment by andyljones** [comment]
Hey chstan - while I can see how this'd be useful, I don't have the slack to implement or support it here. If you're happy to maintain the variant yourself, say and I'll add a link to your project from the readme.
