### ISSUE TITLE
Errors despite Xorg and nvidia-settings/smi on PATH.

### ISSUE THREAD

**Issue by TimDettmers** [andyljones/coolgpus#2]
I just looked at this again. I got some weird behavior where I could run it the twice just fine, but then I aborted it with Ctrl+c twice (not a smooth termination of XServers) and now I can no longer run it. On another machine, I get the same error from the start (it never worked):
```
Traceback (most recent call last):
  File "/home/tim/anaconda3/bin/coolgpus", line 177, in <module>
    run()
  File "/home/tim/anaconda3/bin/coolgpus", line 174, in run
    manage_fans(displays)
  File "/home/tim/anaconda3/bin/coolgpus", line 168, in manage_fans
    assign(display, '[gpu:0]/GPUFanControlState=0')
  File "/home/tim/anaconda3/bin/coolgpus", line 143, in assign
    check_output(['nvidia-settings', '-a', command, '-c', display], stderr=STDOUT)
  File "/home/tim/anaconda3/lib/python3.7/subprocess.py", line 395, in check_output
    **kwargs).stdout
  File "/home/tim/anaconda3/lib/python3.7/subprocess.py", line 487, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['nvidia-settings', '-a', '[gpu:0]/GPUFanControlState=0', '-c', ':0']' returned non-zero exit status 1.
```

I tried to figure it out but was not able to (Xorg, nvidia-settings, and nvidia-smi are on PATH). The XServers seem to be starting just fine. Do you have any ideas on how to debug this?

**Comment by andyljones** [comment]
For the first computer: I suspect there're some subprocesses from the double-killed launch hanging around. See if `sudo ps -ef | grep Xorg` shows any processes pointing at `cool-gpus` configs, like these:
```
root      26173  26171  0 09:18 tty2     00:00:00 /usr/lib/xorg/Xorg :0 -once -config /tmp/cool-gpu-00000000:08:00.0uwcIr4/xorg.conf
root      26174  26171  0 09:18 ?        00:00:00 /usr/lib/xorg/Xorg :1 -once -config /tmp/cool-gpu-00000000:41:00.0vwvZ53/xorg.conf
```
then kill them with `sudo pkill -f /tmp/coolgpu`

For the second computer: I've updated the script to v0.13 and added some subprocess logging. Mind running it again and copy-pasting me the whole output?

**Comment by TimDettmers** [comment]
On my second system, it seems that it was a running Xorg server issue. It is a headless system but runs a Ubuntu desktop OS which restarts Xorg continuously. What I found works best is to use `sudo killall -9 Xorg && sleep 0.5 && sudo $(which coolgpus) --speed 99 99` but even that does not work 100% of the time. However, it worked for me always after a couple of tries, so it seems to be a timing issue. Sometimes the problem is that the Xorg server has not completely shut down yet and the new Xorg servers cannot connect:
```
Unable to init server: Could not connect: Connection refused

ERROR: Unable to find display on any available system
```

The first system is actually my desktop computer which has displays but which I was accessing remotely. When I was running the first few commands it still worked (fan control on all GPUs which were not attached to displays), but I cannot get it working again now. But since this is not the main use of the program it should be fine — I was surprised that it was working at all for a headed machine.

I will give you the error messages anyway since it might help you to get more insights into this.

Here the error message anyway. Maybe it might help you to make progress on headed machines. The first error is similar to the one above where a connection is refused, the second one says `Invalid MIT-MAGIC-COOKIE-1 key`

First:
```
Starting xserver: Xorg :0 -once -config /tmp/cool-gpu-00000000:09:00.00vtj1bdn/xorg.conf
Starting xserver: Xorg :1 -once -config /tmp/cool-gpu-00000000:0B:00.0doavi8lg/xorg.conf
Starting xserver: Xorg :2 -once -config /tmp/cool-gpu-00000000:43:00.0b0wzrvqj/xorg.conf
Starting xserver: Xorg :3 -once -config /tmp/cool-gpu-00000000:45:00.0ai8xkb2n/xorg.conf
Unable to init server: Could not connect: Connection refused

ERROR: Unable to find display on any available system


ERROR: Unable to find display on any available system


Unable to init server: Could not connect: Connection refused

ERROR: Unable to find display on any available system


ERROR: Unable to find display on any available system


Terminating xserver for display :0
Terminating xserver for display :1
Terminating xserver for display :2
Terminating xserver for display :3
Traceback (most recent call last):
  File "/home/tim/anaconda3/bin/coolgpus", line 172, in manage_fans
    set_speed(display, s)
  File "/home/tim/anaconda3/bin/coolgpus", line 158, in set_speed
    assign(display, '[gpu:0]/GPUFanControlState=1')
  File "/home/tim/anaconda3/bin/coolgpus", line 155, in assign
    log_output(['nvidia-settings', '-a', command, '-c', display])
  File "/home/tim/anaconda3/bin/coolgpus", line 88, in log_output
    raise ValueError('Command ' + ' '.join(command) + ' crashed with return code ' + str(p.returncode) + ':')
ValueError: Command nvidia-settings -a [gpu:0]/GPUFanControlState=1 -c :0 crashed with return code 1:

```

Second:
```
Starting xserver: Xorg :0 -once -config /tmp/cool-gpu-00000000:09:00.0s7m3sol5/xorg.conf
Starting xserver: Xorg :1 -once -config /tmp/cool-gpu-00000000:0B:00.0o6sf09o2/xorg.conf
Starting xserver: Xorg :2 -once -config /tmp/cool-gpu-00000000:43:00.06a4wy7j_/xorg.conf
Starting xserver: Xorg :3 -once -config /tmp/cool-gpu-00000000:45:00.07ec89__t/xorg.conf
(EE) 
Fatal server error:
(EE) Server is already active for display 0
	If this server is no longer running, remove /tmp/.X0-lock
	and start again.
(EE) 
(EE) 
Please consult the The X.Org Foundation support 
	 at http://wiki.x.org
 for help. 
(EE) 

X.Org X Server 1.19.6
Release Date: 2017-12-20
X Protocol Version 11, Revision 0
Build Operating System: Linux 4.4.0-138-generic x86_64 Ubuntu
Current Operating System: Linux tim-uw 4.15.0-65-generic #74-Ubuntu SMP Tue Sep 17 17:06:04 UTC 2019 x86_64
Kernel command line: BOOT_IMAGE=/boot/vmlinuz-4.15.0-65-generic root=UUID=c4bc0994-b43e-4f5e-b5a4-96be8e874ac2 ro quiet splash nvidia-drm.modeset=1 vt.handoff=1
Build Date: 25 October 2018  04:11:27PM
xorg-server 2:1.19.6-1ubuntu4.2 (For technical support please see http://www.ubuntu.com/support) 
Current version of pixman: 0.34.0
	Before reporting problems, check http://wiki.x.org
	to make sure that you have the latest version.
Markers: (--) probed, (**) from config file, (==) default setting,
	(++) from command line, (!!) notice, (II) informational,
	(WW) warning, (EE) error, (NI) not implemented, (??) unknown.
(==) Log file: "/var/log/Xorg.2.log", Time: Tue Oct 15 20:34:00 2019
(++) Using config file: "/tmp/cool-gpu-00000000:43:00.06a4wy7j_/xorg.conf"
(==) Using system config directory "/usr/share/X11/xorg.conf.d"

X.Org X Server 1.19.6
X.Org X Server 1.19.6
Release Date: 2017-12-20

Release Date: 2017-12-20
X Protocol Version 11, Revision 0
X Protocol Version 11, Revision 0
Build Operating System: Linux 4.4.0-138-generic x86_64 Ubuntu
Build Operating System: Linux 4.4.0-138-generic x86_64 Ubuntu
Current Operating System: Linux tim-uw 4.15.0-65-generic #74-Ubuntu SMP Tue Sep 17 17:06:04 UTC 2019 x86_64
Current Operating System: Linux tim-uw 4.15.0-65-generic #74-Ubuntu SMP Tue Sep 17 17:06:04 UTC 2019 x86_64
Kernel command line: Kernel command line: BOOT_IMAGE=/boot/vmlinuz-4.15.0-65-generic root=UUID=c4bc0994-b43e-4f5e-b5a4-96bBOOT_IMAGE=/boot/vmlinuz-4.15.0-65-generic root=UUID=c4bc0994-b43e-4f5e-b5a4-96be8e874ac2 ro quiet splash nvidia-drm.modeset=1 vt.handoff=1
e8e874ac2 ro quiet splash nvidia-drm.modeset=1 vt.handoff=1
Build Date: 25 October 2018  04:11:27PM
Build Date: 25 October 2018  04:11:27PM
xorg-server 2:1.19.6-1ubuntu4.2 (For technical support please see http://www.ubuntu.com/support) 
xorg-server 2:1.19.6-1ubuntu4.2 (For technical support please see http://www.ubuntu.com/support) 
Current version of pixman: 0.34.0
Current version of pixman: 0.34.0
	Before reporting problems, check http://wiki.x.org
	to make sure that you have the latest version.
	Before reporting problems, check http://wiki.x.org
	to make sure that you have the latest version.
Markers: Markers: (--) probed, (**) from config file, (--) probed, (==) default setting,
	(**) from config file, (++) from command line, (==) default setting,
	(!!) notice, (++) from command line, (II) informational,
	(!!) notice, (WW) warning, (II) informational,
	(EE) error, (WW) warning, (NI) not implemented, (EE) error, (??) unknown.
(NI) not implemented, (??) unknown.
(==) Log file: "/var/log/Xorg.1.log", Time: Tue Oct 15 20:34:00 2019
(==) Log file: "/var/log/Xorg.3.log", Time: Tue Oct 15 20:34:00 2019
(++) Using config file: "/tmp/cool-gpu-00000000:0B:00.0o6sf09o2/xorg.conf"
(++) Using config file: "/tmp/cool-gpu-00000000:45:00.07ec89__t/xorg.conf"
(==) Using system config directory "/usr/share/X11/xorg.conf.d"
(==) Using system config directory "/usr/share/X11/xorg.conf.d"
Unable to init server: Could not connect: Connection refused
Invalid MIT-MAGIC-COOKIE-1 key
ERROR: Unable to find display on any available system

Invalid MIT-MAGIC-COOKIE-1 key
ERROR: Unable to find display on any available system


Unable to init server: Could not connect: Connection refused
Invalid MIT-MAGIC-COOKIE-1 key
ERROR: Unable to find display on any available system

Invalid MIT-MAGIC-COOKIE-1 key
ERROR: Unable to find display on any available system


Terminating xserver for display :0
Terminating xserver for display :1
Terminating xserver for display :2
Terminating xserver for display :3
Traceback (most recent call last):
  File "/home/tim/anaconda3/bin/coolgpus", line 172, in manage_fans
    set_speed(display, s)
  File "/home/tim/anaconda3/bin/coolgpus", line 158, in set_speed
    assign(display, '[gpu:0]/GPUFanControlState=1')
  File "/home/tim/anaconda3/bin/coolgpus", line 155, in assign
    log_output(['nvidia-settings', '-a', command, '-c', display])
  File "/home/tim/anaconda3/bin/coolgpus", line 88, in log_output
    raise ValueError('Command ' + ' '.join(command) + ' crashed with return code ' + str(p.returncode) + ':')
ValueError: Command nvidia-settings -a [gpu:0]/GPUFanControlState=1 -c :0 crashed with return code 1:

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/tim/anaconda3/bin/coolgpus", line 189, in <module>
    run()
  File "/home/tim/anaconda3/bin/coolgpus", line 186, in run
    manage_fans(displays)
  File "/home/tim/anaconda3/bin/coolgpus", line 180, in manage_fans
    assign(display, '[gpu:0]/GPUFanControlState=0')
  File "/home/tim/anaconda3/bin/coolgpus", line 155, in assign
    log_output(['nvidia-settings', '-a', command, '-c', display])
  File "/home/tim/anaconda3/bin/coolgpus", line 88, in log_output
    raise ValueError('Command ' + ' '.join(command) + ' crashed with return code ' + str(p.returncode) + ':')
ValueError: Command nvidia-settings -a [gpu:0]/GPUFanControlState=0 -c :0 crashed with return code 1:
```

**Comment by andyljones** [comment]
Thanks for the logs! I think it only _looks_ like it's working on your desktop, because the `nvidia-settings` calls can hijack the existing X servers. The problem is that the existing X servers might not be numbered in the same order as the GPU bus IDs, in which case the script might set a GPU's fan speed based on another GPU's temperature. 

That seems like enough of an issue that I've added a check as to whether any X servers are currently running, and a `--kill` switch to get rid of any them if you want to. It's only a half-fix though, as it doesn't deal with Ubuntu rebooting the X displays.

**Comment by TimDettmers** [comment]
That sounds good. Thanks for all your help, Andy. As I said I will advertise your library — it will be useful to a lot of people!

**Comment by sdsy888** [comment]
> Thanks for the logs! I think it only _looks_ like it's working on your desktop, because the `nvidia-settings` calls can make use of the existing X servers. The problem is that the existing X servers might not be numbered in the same order as the GPU bus IDs, in which case the script might set a GPU's fan speed based on another GPU's temperature.
> 
> That seems like enough of an issue that I've added a check as to whether any X servers are currently running, and a `--kill` switch to get rid of any them if you want to. It's only a half-fix though, as it doesn't deal with Ubuntu rebooting the X displays. Getting Ubuntu to stop doing that [looks complicated](https://unix.stackexchange.com/questions/25668/how-to-close-x-server-to-avoid-errors-while-updating-nvidia-driver) and is probably, unfortunately, best left to the user.

Hi andy, thanks for your great work!

I can use it normally at first, but after I stop it and re-run the same command, it reports the same error like above:

```
ValueError: Command nvidia-settings -a [gpu:0]/GPUFanControlState=0 -c :0 crashed with return code 1:
```

and the command I use is:
```
sudo $(which coolgpus) --temp 17 84 --speed 15 90 --kill
```

Do you have any clue how to fix this? Thank you in advance.

**Comment by sdsy888** [comment]
> > Thanks for the logs! I think it only _looks_ like it's working on your desktop, because the `nvidia-settings` calls can make use of the existing X servers. The problem is that the existing X servers might not be numbered in the same order as the GPU bus IDs, in which case the script might set a GPU's fan speed based on another GPU's temperature.
> > That seems like enough of an issue that I've added a check as to whether any X servers are currently running, and a `--kill` switch to get rid of any them if you want to. It's only a half-fix though, as it doesn't deal with Ubuntu rebooting the X displays. Getting Ubuntu to stop doing that [looks complicated](https://unix.stackexchange.com/questions/25668/how-to-close-x-server-to-avoid-errors-while-updating-nvidia-driver) and is probably, unfortunately, best left to the user.
> 
> Hi andy, thanks for your great work!
> 
> I can use it normally at first, but after I stop it and re-run the same command, it reports the same error like above:
> 
> ```
> ValueError: Command nvidia-settings -a [gpu:0]/GPUFanControlState=0 -c :0 crashed with return code 1:
> ```
> 
> and the command I use is:
> 
> ```
> sudo $(which coolgpus) --temp 17 84 --speed 15 90 --kill
> ```
> 
> Do you have any clue how to fix this? Thank you in advance.

magicall, after I relogin to my server, no error report at all....

**Comment by andyljones** [comment]
The command that's causing the crash is shown there - if it happens again then try running it directly in the terminal, and see if it's any more informative
```
nvidia-settings -a [gpu:0]/GPUFanControlState=0 -c :0
```
That aside, the fact that it only crashed after you stopped makes me think you might have hit Ctrl+C twice when stopping it and interrupted the shutdown procedure. There's a note in the readme about this, though it regards a different kind of bug:
> You hit Ctrl+C twice and now your fans are stuck at a certain speed: run the script again and interrupt it once, then let it shut down gracefully. Double interrupts stop it from handing control back to the driver. Don't double-interrupt things you barbarian.

**Comment by sdsy888** [comment]
> The command that's causing the crash is shown there - if it happens again then try running it directly in the terminal, and see if it's any more informative
> 
> ```
> nvidia-settings -a [gpu:0]/GPUFanControlState=0 -c :0
> ```
> 
> That aside, the fact that it only crashed after you stopped makes me think you might have hit Ctrl+C twice when stopping it and interrupted the shutdown procedure. There's a note in the readme about this, though it regards a different kind of bug:
> 
> > You hit Ctrl+C twice and now your fans are stuck at a certain speed: run the script again and interrupt it once, then let it shut down gracefully. Double interrupts stop it from handing control back to the driver.

ok, cool! thank you for your reply! 
It's a wonderful tool and I believe it should be known to more people.

**Comment by sdsy888** [comment]
> > The command that's causing the crash is shown there - if it happens again then try running it directly in the terminal, and see if it's any more informative
> > ```
> > nvidia-settings -a [gpu:0]/GPUFanControlState=0 -c :0
> > ```
> > 
> > 
> > That aside, the fact that it only crashed after you stopped makes me think you might have hit Ctrl+C twice when stopping it and interrupted the shutdown procedure. There's a note in the readme about this, though it regards a different kind of bug:
> > > You hit Ctrl+C twice and now your fans are stuck at a certain speed: run the script again and interrupt it once, then let it shut down gracefully. Double interrupts stop it from handing control back to the driver.
> 
> ok, cool! thank you for your reply!
> It's a wonderful tool and I believe it should be known to more people.

btw, already recommended this great repo on my Chinese blog: https://blog.csdn.net/songyu0120/article/details/105912206
http://sdsy888.me/工具-Tools/2020/Nvidia-GPU风扇转速自动调节/

**Comment by andyljones** [comment]
That's fantastic, thanks for both writing it and sharing it back with me. 谢谢! 😄

**Comment by sdsy888** [comment]
> The command that's causing the crash is shown there - if it happens again then try running it directly in the terminal, and see if it's any more informative
> 
> ```
> nvidia-settings -a [gpu:0]/GPUFanControlState=0 -c :0
> ```
> 
> That aside, the fact that it only crashed after you stopped makes me think you might have hit Ctrl+C twice when stopping it and interrupted the shutdown procedure. There's a note in the readme about this, though it regards a different kind of bug:
> 
> > You hit Ctrl+C twice and now your fans are stuck at a certain speed: run the script again and interrupt it once, then let it shut down gracefully. Double interrupts stop it from handing control back to the driver.

Hi @andyljones , unfortunately, the problem happens again. Here's the log info:

```
No existing X servers, we're good to go
Starting xserver: Xorg :0 -once -config /tmp/cool-gpu-00000000:05:00.0jting9z8/xorg.conf
Starting xserver: Xorg :1 -once -config /tmp/cool-gpu-00000000:06:00.0wnnwlgxr/xorg.conf
Starting xserver: Xorg :2 -once -config /tmp/cool-gpu-00000000:09:00.0metfkth1/xorg.conf
Starting xserver: Xorg :3 -once -config /tmp/cool-gpu-00000000:0A:00.0artlu8gw/xorg.conf
Unable to init server: Could not connect: Connection refused

ERROR: Unable to find display on any available system


ERROR: Unable to find display on any available system


Unable to init server: Could not connect: Connection refused

ERROR: Unable to find display on any available system


ERROR: Unable to find display on any available system


Terminating xserver for display :0
Terminating xserver for display :1
Terminating xserver for display :2
Terminating xserver for display :3
Traceback (most recent call last):
  File "/media/newhd/ysong/anaconda3/envs/pytorch1.4/bin/coolgpus", line 225, in manage_fans
    set_speed(display, s)
  File "/media/newhd/ysong/anaconda3/envs/pytorch1.4/bin/coolgpus", line 211, in set_speed
    assign(display, '[gpu:0]/GPUFanControlState=1')
  File "/media/newhd/ysong/anaconda3/envs/pytorch1.4/bin/coolgpus", line 208, in assign
    log_output(['nvidia-settings', '-a', command, '-c', display])
  File "/media/newhd/ysong/anaconda3/envs/pytorch1.4/bin/coolgpus", line 91, in log_output
    raise ValueError('Command ' + ' '.join(command) + ' crashed with return code ' + str(p.returncode) + ':')
ValueError: Command nvidia-settings -a [gpu:0]/GPUFanControlState=1 -c :0 crashed with return code 1:

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/media/newhd/ysong/anaconda3/envs/pytorch1.4/bin/coolgpus", line 242, in <module>
    run()
  File "/media/newhd/ysong/anaconda3/envs/pytorch1.4/bin/coolgpus", line 239, in run
    manage_fans(displays)
  File "/media/newhd/ysong/anaconda3/envs/pytorch1.4/bin/coolgpus", line 233, in manage_fans
    assign(display, '[gpu:0]/GPUFanControlState=0')
  File "/media/newhd/ysong/anaconda3/envs/pytorch1.4/bin/coolgpus", line 208, in assign
    log_output(['nvidia-settings', '-a', command, '-c', display])
  File "/media/newhd/ysong/anaconda3/envs/pytorch1.4/bin/coolgpus", line 91, in log_output
    raise ValueError('Command ' + ' '.join(command) + ' crashed with return code ' + str(p.returncode) + ':')
ValueError: Command nvidia-settings -a [gpu:0]/GPUFanControlState=0 -c :0 crashed with return code 1:
```

Also, I didn't use double "ctrl+c" this time to stop the `coolgpus`. Here's the log after I run `nvidia-settings -a "[gpu:0]/GPUFanControlState=0 -c :0"`.:
```
Unable to init server: Could not connect: Connection refused

ERROR: The control display is undefined; please run `nvidia-settings --help` for usage information.

(pytorch1.4) ➜  ~ sudo nvidia-settings -a "[gpu:0]/GPUFanControlState=0 -c :0"
Unable to init server: Could not connect: Connection refused

ERROR: The control display is undefined; please run `nvidia-settings --help` for usage information.
```

Btw, last time when the same problem happens, it just went back to normal somehow. I didn't do anything then. But this time I didn't get luck.

So, do you know how to solve it or in what way can I try next time?
Thank you in advance.

**Comment by andyljones** [comment]
That's weird. I have no idea what's causing it, so I'm gonna give you some pointers on how I'd go about figuring it out.

OK, some treating-the-symptoms first:

  * Is there anything unusual about your system? 
  * What Python version are you running? 
  * What OS are you running?
  * Do you have any monitors attached to the server?
  * Have you tried restarting the server? 
  * Did you manually stop coolgpus previously and it crashed when you tried to start again, or has it been running in the background and it crashed spontaneously?

My spidey-sense is that the X servers the script sets up are either dying or not launching in the first place for some reason, and then `nvidia-settings` is complaining it can't find them. Two ways to check on the X servers are with `nvidia-smi` (which should list one per GPU) and `ps -ef | grep Xorg`. There should be at most one X server per GPU, and there shouldn't be any that look like they were launched by something other than coolgpus. If there are, something is rotten.

Anyway, `coolgpus` prints out all the commands it uses, so you can replicate it manually in just this kind of situation. So:

  * What's the output look like from launching one of the Xorg servers yourself? ie, try running
  ```sudo Xorg :0 -once -config /tmp/cool-gpu-00000000:05:00.0jting9z8/xorg.conf```
  * This should work because the tmp directory should have outlived coolgpu's process. If it didn't - if the `/tmp/cool-gpu-blah-blah` dir no longer exists - you'll need to try the debugger version of all this below.
  * If the server seems to launch okay, great! Check it turns up in `nvidia-smi`, then use `sudo pkill Xorg` to kill the server. Then run all four of the Xorg commands from the logs, and see if any of them 'look weird'. Check they also show up in `nvidia-smi`/`ps -ef " grep Xorg`. 
  * If that all worked fine, now run the `sudo nvidia-settings` command manually and check you get the same error the script does.
  * If you do all that and there's no error but there _is_ when you run the script, I am stumped.
  * NB: make sure you run all these commands `sudo`. 

If the tmp dirs have been destroyed, or if it turns out it all works fine when done manually, the next trick is more involved.

  * Open the script in your preferred text editor. I'd use `nvim $(which coolgpus)`, but you might use something different.
  * Add `breakpoint()` after the `for bus, display...` line. This'll hold the process open with the debugger after all the config files are generated so the tmp dirs don't go anywhere.  
  * Save it and run the edited script as you would normally 
  * Use `sudo pkill Xorg` to kill all the display servers, then launch them manually in a separate terminal like above. 
  * Run the `sudo nvidia-settings` command manually, and, if it works, try again from within the debugger with `set_speed(display, 100)`. 
  * If _that_ works but the script as a whole doesn't work, I am stumped.

**Comment by sdsy888** [comment]
> That's weird. I have no idea what's causing it, so I'm gonna give you some pointers on how I'd go about figuring it out. Read all of this before starting on any part of it; there's likely some combination of what you know and I don't, and what I know but you don't, that will figure this out much more quickly than just following my instructions.
> 
> OK, some treating-the-symptoms first:
> 
> * Is there anything unusual about your system?
> * What Python version are you running?
> * What OS are you running?
> * Do you have any monitors attached to the server?
> * Have you tried restarting the server?
> * Did you manually stop coolgpus previously and it crashed when you tried to start again, or has it been running in the background and it crashed spontaneously?
> 
> My spidey-sense is that the X servers the script sets up are either dying or not launching in the first place for some reason, and then `nvidia-settings` is complaining it can't find them. Two ways to check on the X servers are with `nvidia-smi` (which should list one per GPU) and `ps -ef | grep Xorg`. There should be at most one X server per GPU, and there shouldn't be any that look like they were launched by something other than coolgpus. If there are, something is rotten.
> 
> Anyway, `coolgpus` prints out all the commands it uses, so you can replicate it manually in just this kind of situation. So:
> 
> * What's the output look like from launching one of the Xorg servers yourself? ie, try running
>   `sudo Xorg :0 -once -config /tmp/cool-gpu-00000000:05:00.0jting9z8/xorg.conf`
> * This should work because the tmp directory should have outlived coolgpu's process. If it didn't - if the `/tmp/cool-gpu-blah-blah` dir no longer exists - you'll need to try the debugger version of all this below.
> * If the server seems to launch okay, great! Check it turns up in `nvidia-smi`, then use `sudo pkill Xorg` to kill the server. Then run all four of the Xorg commands from the logs, and see if any of them 'look weird'. Check they also show up in `nvidia-smi`/`ps -ef " grep Xorg`.
> * If that all worked fine, now run the `sudo nvidia-settings` command manually and check you get the same error the script does.
> * If you do all that and there's no error but there _is_ when you run the script, I am stumped.
> * NB: make sure you run all these commands `sudo`.
> 
> If the tmp dirs have been destroyed, or if it turns out it all works fine when done manually, the next trick is more involved.
> 
> * Open the script in your preferred text editor. I'd use `nvim $(which coolgpus)`, but you might use something different.
> * Add `breakpoint()` after the `for bus, display...` line. This'll hold the process open with the debugger after all the config files are generated so the tmp dirs don't go anywhere.
> * Save it and run the edited script as you would normally
> * Use `sudo pkill Xorg` to kill all the display servers, then launch them manually in a separate terminal like above.
> * Run the `sudo nvidia-settings` command manually, and, if it works, try again from within the debugger with `set_speed(display, 100)`.
> * If _that_ works but the script as a whole doesn't work, I am stumped.
> 
> What I'm very much expecting is that when you try to manually run the `Xorg` command, it complains about some bit of your particular system. What I'm expecting less but still substantially is that the command runs fine and then the corresponding server later mysteriously disappears from `nvidia-smi`.

thank you for the quick reply! I  solve the problem last time by restarting the machine. The next time it happens, I'll update the result of the solution you provide above.

**Comment by soheil** [comment]
You can do `sudo service gdm stop` to stop the X server.
