### ISSUE TITLE
An improvement of the systemd unit file

### ISSUE THREAD

**Issue by morfast** [andyljones/coolgpus#5]
According the test on my machine, the killmode and kill signal should be specified in the systemd unit file (added to the [Service] section) :

ExecStop=/bin/kill -2 $MAINPID
KillMode=none

Otherwise, when executing "systemctl stop", the default SIGTERM signal will be sent to the main process(python) and child process(Xorg), result in the fan speed control not be released, the "assign(display, '[gpu:0]/GPUFanControlState=0')" statment will not be executed, and the fan speed control will not return to the stock automode.

Anyway, thanks very much, it's a wonderful tool and it solved my fan speed control problem.

**Comment by andyljones** [comment]
Thanks very much! I've added your suggestion and I've credited you in the readme. I've used the name from your Github page, but say if you'd prefer something else.
