### ISSUE TITLE
f'temp and speed should have the same length'

### ISSUE THREAD

**Issue by Neolo** [andyljones/coolgpus#6]
sudo $(which coolgpus) --speed 99 99
  File "/usr/bin/coolgpus", line 28
    assert len(args.temp) == len(args.speed), f'temp and speed should have the same length'
                                                                                          ^
SyntaxError: invalid syntax

**Huh??**

**Comment by Neolo** [comment]
Edit coolgpus file and set python 3.6 or higher

**Comment by v-iashin** [comment]
I think that was my PR so I will respond. Indeed, there is no reason for string formatting in this case but it breaks python version compatibility. Maybe I wanted to format them somehow, then, decided not to, and forgot to remove `f` prefixes. 

@andyljones can we fix it in the next update just by removing `f` prefix?

**Comment by Neolo** [comment]
This issue was cosmetical, the major issue followed in ticket https://github.com/andyljones/coolgpus/issues/7
Not sure if also related to python version, but feels like loop is just not looping at all. No errors.

**Comment by andyljones** [comment]
done
